title: Site

sections:
  pages:
    type: pages
    template: ['home','about','exhibitors']

  fields:
    type: fields
    fields:
      color:
        label: Color
        type: color
      footer_header:
        label: Footer Header
        type: writer
        nodes: false
        marks: []
        width: 1/2
      footer_columns:
        label: Footer Columns
        type: blocks
        width: 1/2
        fieldsets:
          body_text:
            label: Body Text
            fields:
              text:
                type: writer
                nodes: false
                marks: [italic, link]
